"""Circuit Solver Module for simulating linear and non-linear circuits.

This module provides the core mathematical solvers for the Modified Nodal
Analysis (MNA) equations generated by the physical circuit components. It 
implements both standard direct sparse LU factorization and an advanced 
Explicit Woodbury Strategy for O(1) localized large-change sensitivity analysis. 

Furthermore, it features a highly robust, cascading Newton-Raphson nonlinear 
solver with built-in failsafe algorithms (Damped Stepping, Source Stepping, 
and GMIN Stepping) to guarantee convergence for volatile non-linear systems.
"""

import numpy as np
import scipy.sparse as sp
from scipy.sparse.linalg import spsolve, splu

class ConvergenceError(Exception):
    """Raised when a nonlinear solving strategy fails to converge within tolerances."""
    pass

# =========================================================================
# LINEAR SOLVERS & UTILITIES
# =========================================================================

def solve_lu(g):
    """Performs SuperLU factorization on a sparse admittance matrix.

    Args:
        g (scipy.sparse.csc_matrix): The global MNA admittance matrix in 
            Compressed Sparse Column format.

    Returns:
        scipy.sparse.linalg.SuperLU: The factorized LU object, which can be 
        cached and reused to quickly solve multiple RHS vectors without 
        re-inverting the matrix.
    """
    return splu(g)

def get_node_and_branch_currents(lu, sources):
    """Solves the linear system using a pre-computed LU factorization.

    Args:
        lu (scipy.sparse.linalg.SuperLU): The factorized matrix object.
        sources (numpy.ndarray): The Right-Hand Side (RHS) vector containing 
            independent and equivalent source currents/voltages.

    Returns:
        numpy.ndarray: The resolved state vector containing absolute node 
        voltages and auxiliary branch currents.
    """
    return lu.solve(sources)

def solve_linear_circuit(y, sources):
    """Solves a complete linear circuit equation in a single pass.

    This acts as a convenience wrapper around `solve_lu` and 
    `get_node_and_branch_currents`.

    Args:
        y (scipy.sparse.csc_matrix): The full MNA admittance matrix.
        sources (numpy.ndarray): The RHS source vector.

    Returns:
        tuple[scipy.sparse.linalg.SuperLU, numpy.ndarray]: A tuple containing 
        the cached LU factorization object and the solved state vector.
    """
    lu = solve_lu(y)
    vi = get_node_and_branch_currents(lu, sources)
    return lu, vi

def solve_adjoint(lu, target, circuit):
    """Solves the transposed matrix equation for Adjoint sensitivity analysis.

    Injects a mathematical impulse (1.0) at the target output node and solves 
    the system backward using the cached forward LU factorization.

    Args:
        lu (scipy.sparse.linalg.SuperLU): Cached LU factorization from the 
            forward simulation pass.
        target (str or int): The netlist name or integer ID of the objective 
            output node.
        circuit (Circuit): The active circuit orchestrator, used for node 
            index lookups.

    Returns:
        numpy.ndarray: The adjoint state vector (Psi/Phi) mapping the sensitivity 
        of the target output to every node in the circuit.
    """
    d = np.zeros(circuit.total_dim)
    idx = circuit.get_idx(target)
    
    if idx is not None:
        d[idx] = 1.0
        
    return lu.solve(d, trans='T')

# =========================================================================
# SOLVER STRATEGIES (For Parameter Sweeps and Large Change Analysis)
# =========================================================================

class StandardDirectStrategy:
    """The traditional solving approach using full LU factorization per step."""
    
    def solve_step(self, circuit, v_k, domain, t, dt, v_prev, method, gmin=0.0, source_scale=1.0):
        """Builds and solves the sparse global matrix natively.

        Args:
            circuit (Circuit): The active circuit orchestrator.
            v_k (numpy.ndarray): The current Newton-Raphson iteration guess.
            domain (str): The simulation domain ('static', 'time', 'frequency').
            t (float): The current simulation time in seconds.
            dt (float): The integration time step in seconds.
            v_prev (numpy.ndarray): The converged state from the previous time step.
            method (str): The integration method ('TR' or 'BE').
            gmin (float, optional): Artificial ground conductance to inject. Defaults to 0.0.
            source_scale (float, optional): Multiplier for independent sources. Defaults to 1.0.

        Returns:
            tuple[scipy.sparse.linalg.SuperLU, numpy.ndarray]: The LU factorization 
            and the resulting evaluated state vector.
        """
        # 1. Build the full global Y matrix and J vector
        Y_iter, J_iter = circuit.build_system(
            domain=domain, t=t, dt=dt, v_prev=v_prev, v_k=v_k, method=method
        )
        
        # 2. Apply Solver Interventions
        if source_scale != 1.0:
            J_iter *= source_scale
            
        if gmin > 0.0:
            gmin_matrix = sp.diags([gmin], [0], shape=(circuit.total_dim, circuit.total_dim))
            Y_iter = Y_iter + gmin_matrix
            
        # 3. LU Factorize the full O(N x N) matrix
        lu = splu(Y_iter.tocsc())
        v_new = lu.solve(J_iter)
        
        return lu, v_new

class ExplicitWoodburyStrategy:
    
    def __init__(self, circuit, param_names, lu_base, v_nom, dp_array=None):
        self.lu_base = lu_base
        self.v_nom = v_nom  
        self.comp_to_shifts = {}
        swept_comps = set()
        
        if dp_array is not None:
            for p, dp in zip(param_names, dp_array):
                comp = circuit.param_to_component_map[p]
                swept_comps.add(comp)
                if comp not in self.comp_to_shifts:
                    self.comp_to_shifts[comp] = {}
                self.comp_to_shifts[comp][p] = dp

        nl_comps = set(getattr(circuit, '_nl_comps', []))
        self.active_components = list(swept_comps.union(nl_comps))
        
        self.N = circuit.total_dim
        
        self.comp_indices = {}
        self.k = 0
        
        for comp in self.active_components:
            rank = getattr(comp, 'rank', 1) # Default to 1 if not specified
            self.comp_indices[comp] = (self.k, self.k + rank)
            self.k += rank
            
        self.P = np.zeros((self.N, self.k))
        self.Q = np.zeros((self.N, self.k))
        
        for comp in self.active_components:
            start_idx, _ = self.comp_indices[comp]
            comp.stamp_PQ(self.P, self.Q, start_idx)

        self.X = self.lu_base.solve(self.P)
        self.QT_X = self.Q.T @ self.X


    def solve_step(self, circuit, v_k, domain, t, dt, v_prev, method, gmin=0.0, source_scale=1.0):
        """Solves the system using the Woodbury matrix identity instead of LU.

        If GMIN stepping modifies the global topology, this method safely falls 
        back to the `StandardDirectStrategy` for the current step.

        Args:
            circuit (Circuit): The active circuit orchestrator.
            v_k (numpy.ndarray): The current Newton-Raphson iteration guess.
            domain (str): The simulation domain ('static', 'time', 'frequency').
            t (float): The current simulation time in seconds.
            dt (float): The integration time step in seconds.
            v_prev (numpy.ndarray): The converged state from the previous time step.
            method (str): The integration method ('TR' or 'BE').
            gmin (float, optional): Artificial ground conductance to inject. Defaults to 0.0.
            source_scale (float, optional): Multiplier for independent sources. Defaults to 1.0.

        Returns:
            tuple[scipy.sparse.linalg.SuperLU, numpy.ndarray]: The cached baseline 
            LU factorization and the newly calculated state vector.
        """
        if gmin > 0.0:
            fallback = StandardDirectStrategy()
            return fallback.solve_step(circuit, v_k, domain, t, dt, v_prev, method, gmin, source_scale)

        # 1. RHS Extraction (Bypasses sparse matrix allocation!)
        J_iter = circuit.build_rhs_only(
            domain=domain, t=t, dt=dt, v_prev=v_prev, v_k=v_k, method=method
        )
        
        if source_scale != 1.0:
            J_iter *= source_scale

        delta_G = np.zeros((self.k, self.k), dtype=complex if domain=="frequency" else float)
        
        for comp in self.active_components:
            start_idx, end_idx = self.comp_indices[comp]
            shifts_dict = self.comp_to_shifts.get(comp, {})
            
            # Fetch the shift (Could be a scalar for CL, or a 2x2 matrix for MOSFET)
            val = comp.get_delta_y(
                shifts=shifts_dict, V_nom=self.v_nom, V_k=v_k, 
                domain=domain, dt=dt, method=method
            )

            if isinstance(val, np.ndarray):
                delta_G[start_idx:end_idx, start_idx:end_idx] = val
            else:
                delta_G[start_idx, start_idx] = val

        # 3. Standard Woodbury Math
        V_lin = self.lu_base.solve(J_iter)
        QT_V = self.Q.T @ V_lin
        
        M = np.eye(self.k) + delta_G @ self.QT_X
        inv_M = np.linalg.inv(M)
        dV = -self.X @ (inv_M @ (delta_G @ QT_V))
        
        return self.lu_base, V_lin + dV

# =========================================================================
# NONLINEAR SOLVER (The Cascading Orchestrator)
# =========================================================================

class NonlinearSolver:
    """Cascading Newton-Raphson nonlinear solver.

    Tries to solve the nonlinear circuit using standard Newton-Raphson. If it 
    fails due to singular matrices or oscillation, it progressively cascades 
    through slower but more robust strategies to force convergence.
    """

    def __init__(self, circuit, max_iter=100, tol=1e-6, print_stuff=True):
        """Initializes the Nonlinear Solver orchestrator.

        Args:
            circuit (Circuit): The main circuit orchestrator.
            max_iter (int, optional): Max iterations per NR attempt. Defaults to 100.
            tol (float, optional): Voltage error tolerance in Volts. Defaults to 1e-6.
            print_stuff (bool, optional): Toggles console logging output. Defaults to True.
        """
        self.circuit = circuit
        self.max_iter = max_iter
        self.tol = tol
        self.print_stuff = print_stuff

    def solve(self, v_ini, domain="static", t=0.0, dt=0.0, v_prev=None, method="TR", strategy=None):
        """The Master Routing Method. Cascades through fallback options if NR fails.

        Args:
            v_ini (numpy.ndarray): The initial voltage guess vector.
            domain (str, optional): The simulation domain. Defaults to "static".
            t (float, optional): Current simulation time in seconds. Defaults to 0.0.
            dt (float, optional): Current time step size. Defaults to 0.0.
            v_prev (numpy.ndarray, optional): Previous converged voltage state. Defaults to None.
            method (str, optional): Integration method ("TR" or "BE"). Defaults to "TR".
            strategy (object, optional): An injected strategy instance (e.g., ExplicitWoodburyStrategy). 
                Defaults to StandardDirectStrategy if None is provided.

        Returns:
            tuple[scipy.sparse.linalg.SuperLU, numpy.ndarray]: The final factorized 
            matrix and the converged solution array.

        Raises:
            RuntimeError: If all convergence strategies fail.
        """
        if strategy is None:
            strategy = StandardDirectStrategy()
            
        ctx = {
            "domain": domain, "t": t, "dt": dt, 
            "v_prev": v_prev, "method": method, "strategy": strategy
        }

        try:
            if self.print_stuff: print("\n--- Attempting Standard Newton-Raphson ---")
            return self._nr_core(v_ini, alpha=1.0, **ctx)
        except ConvergenceError:
            pass

        try:
            if self.print_stuff: print("\n--- Fallback 1: Damped Newton-Raphson ---")
            return self._nr_core(v_ini, alpha=0.25, **ctx)
        except ConvergenceError:
            pass

        try:
            if self.print_stuff: print("\n--- Fallback 2: Source Stepping ---")
            return self._source_stepping(v_ini, **ctx)
        except ConvergenceError:
            pass

        try:
            if self.print_stuff: print("\n--- Fallback 3: GMIN Stepping ---")
            return self._gmin_stepping(v_ini, **ctx)
        except ConvergenceError:
            raise RuntimeError("CRITICAL: All convergence methods failed.")

    def _nr_core(self, v_guess, domain="static", t=0.0, dt=0.0, v_prev=None, method="TR", alpha=1.0, gmin=0.0, source_scale=1.0, strategy=None):
        """The pure mathematical Newton-Raphson iterative loop.

        Args:
            v_guess (numpy.ndarray): Starting guess for this iteration sequence.
            domain (str): The simulation domain.
            t (float): Current simulation time.
            dt (float): Current time step.
            v_prev (numpy.ndarray): Previous converged voltage state.
            method (str): Integration method.
            alpha (float, optional): Damping multiplier. Defaults to 1.0.
            gmin (float, optional): Artificial ground conductance. Defaults to 0.0.
            source_scale (float, optional): Multiplier for the RHS vector. Defaults to 1.0.
            strategy (object): The dependency-injected matrix resolution strategy.

        Returns:
            tuple[scipy.sparse.linalg.SuperLU, numpy.ndarray]: The finalized LU 
            factorization and the converged vector.

        Raises:
            ConvergenceError: If maximum iterations are reached or matrix becomes singular.
        """
        v_k = v_guess.copy()

        for i in range(self.max_iter):
            # Delegate entirely to the injected strategy
            try:
                lu, v_new = strategy.solve_step(
                    self.circuit, v_k, domain, t, dt, v_prev, method, gmin, source_scale
                )
            except Exception:
                raise ConvergenceError("Matrix became singular.")

            delta_v = np.abs(v_new - v_k)
            max_error = np.max(delta_v)

            max_step = 0.3
            delta_v = v_new - v_k
            delta_v_clamped = np.clip(delta_v, -max_step, max_step)

            v_k = v_k + alpha * delta_v_clamped

            if max_error < self.tol:
                if self.print_stuff: 
                    print(f"  -> Converged in {i+1} iterations (alpha={alpha}, gmin={gmin:.1e}).")
                return lu, v_k

        raise ConvergenceError(f"Failed to converge after {self.max_iter} iterations.")

    def _source_stepping(self, v_guess, **ctx):
        """Slowly scales up independent sources from 10% to 100% to aid convergence."""
        num_steps = 10
        ramp = np.linspace(1.0/num_steps, 1.0, num_steps)
        v_k = v_guess.copy()
        lu = None
        for k in ramp:
            if self.print_stuff: print(f"  Source Step: {k*100:.0f}%")
            lu, v_k = self._nr_core(v_guess=v_k, alpha=1.0, source_scale=k, **ctx)
        return lu, v_k

    def _gmin_stepping(self, v_guess, **ctx):
        """Starts with a massive 1/100 Ohm conductance to ground, stepping down to 1e-12."""
        gmin_steps = np.logspace(-2, -12, num=10)
        v_k = v_guess.copy()
        lu = None
        for g in gmin_steps:
            if self.print_stuff: print(f"  GMIN Step: {g:.1e} Siemens")
            lu, v_k = self._nr_core(v_guess=v_k, alpha=1.0, gmin=g, **ctx)
        if self.print_stuff: print("  Final GMIN Cleanup Pass (0 Siemens)")
        return self._nr_core(v_guess=v_k, alpha=1.0, gmin=0.0, **ctx)
