"""
Circuit Solver Module.

This module handles the core mathematical operations for solving the matrix 
equations generated by the circuit. It includes direct sparse LU factorization 
for linear circuits and an advanced, cascading Newton-Raphson solver for 
nonlinear circuits to ensure robust convergence.
"""

import numpy as np
from scipy.sparse.linalg import spsolve, splu

class ConvergenceError(Exception):
    """Custom exception raised when a nonlinear solving strategy fails to converge."""
    pass


# =========================================================================
# LINEAR SOLVERS
# =========================================================================

def solve_lu(g):
    """Performs SuperLU factorization on a sparse matrix.

    Args:
        g (scipy.sparse.csc_matrix): The Compressed Sparse Column admittance matrix.

    Returns:
        scipy.sparse.linalg.SuperLU: The factorized LU object, which can be cached
        and used to quickly solve multiple RHS vectors (crucial for Adjoint).
    """
    return splu(g)

def get_node_and_branch_currents(lu, sources):
    """Solves the linear system using a pre-computed LU factorization.

    Args:
        lu (scipy.sparse.linalg.SuperLU): The factorized matrix object.
        sources (np.ndarray): The Right-Hand Side (RHS) current/voltage vector.

    Returns:
        np.ndarray: The resolved voltage and branch current vector.
    """
    return lu.solve(sources)

def solve_linear_circuit(y, sources):
    """Solves a complete linear circuit equation in one shot.

    Args:
        y (scipy.sparse.csc_matrix): The full MNA admittance matrix.
        sources (np.ndarray): The RHS source vector.

    Returns:
        tuple: (lu, vi) where `lu` is the factorized matrix object and `vi` is 
        the 1D numpy array of solved node voltages and branch currents.
    """
    lu = solve_lu(y)
    vi = get_node_and_branch_currents(lu, sources)
    return lu, vi

def solve_adjoint(lu, target, circuit):
    """Solves the transposed matrix equation for Adjoint sensitivity analysis.

    Injects a mathematical impulse (1.0) at the target output node and solves 
    the system backward using the cached forward LU factorization.

    Args:
        lu (scipy.sparse.linalg.SuperLU): Cached LU factorization from the forward pass.
        target (str or int): The name or ID of the objective output node.
        circuit (Circuit): The main circuit object for node lookups.

    Returns:
        np.ndarray: The adjoint state vector ($\hat{v}$) for the given time step.
    """
    d = np.zeros(circuit.total_dim)
    idx = circuit.get_idx(target)
    
    if idx is not None:
        d[idx] = 1.0
        
    return lu.solve(d, trans='T')


# =========================================================================
# NONLINEAR SOLVER
# =========================================================================

class NonlinearSolver:
    """Cascading Newton-Raphson nonlinear solver.

    Tries to solve the nonlinear circuit using standard Newton-Raphson. If it 
    fails due to singular matrices or oscillation, it progressively cascades 
    through slower but more robust strategies: Damping, Source Stepping, and 
    GMIN Stepping.

    Attributes:
        circuit (Circuit): The main circuit object.
        max_iter (int): Maximum allowed iterations per NR attempt.
        tol (float): The voltage error tolerance for convergence convergence.
        print_stuff (bool): Toggles console logging.
    """

    def __init__(self, circuit, max_iter=100, tol=1e-6, print_stuff=True):
        """Initializes the Nonlinear Solver.

        Args:
            circuit (Circuit): The populated circuit containing components.
            max_iter (int, optional): Max iterations per NR loop. Defaults to 100.
            tol (float, optional): Convergence tolerance in Volts. Defaults to 1e-6.
            print_stuff (bool, optional): Enable console logging. Defaults to True.
        """
        self.circuit = circuit
        self.max_iter = max_iter
        self.tol = tol
        self.print_stuff = print_stuff

    def solve(self, Y_base_lil, sources_base, v_ini):
        """The Master Routing Method. Cascades through fallback options if NR fails.

        Args:
            Y_base_lil (scipy.sparse.lil_matrix): The static base admittance matrix.
            sources_base (np.ndarray): The static RHS source vector.
            v_ini (np.ndarray): The initial voltage guess vector.

        Returns:
            tuple: (lu, v_final) where `lu` is the final factorized matrix and 
            `v_final` is the converged solution array.

        Raises:
            RuntimeError: If all 4 convergence strategies completely fail.
        """
        # 1. Standard Newton-Raphson (Fastest)
        try:
            if self.print_stuff: print("\n--- Attempting Standard Newton-Raphson ---")
            return self._nr_core(Y_base_lil, sources_base, v_ini, alpha=1.0)
        except ConvergenceError:
            if self.print_stuff: print("Standard NR Failed.")

        # 2. Damped Newton-Raphson (Slower steps to prevent overshoot)
        try:
            if self.print_stuff: print("\n--- Fallback 1: Damped Newton-Raphson ---")
            return self._nr_core(Y_base_lil, sources_base, v_ini, alpha=0.25)
        except ConvergenceError:
            if self.print_stuff: print("Damped NR Failed.")

        # 3. Source Stepping (Slowly turns on the power supplies)
        try:
            if self.print_stuff: print("\n--- Fallback 2: Source Stepping ---")
            return self._source_stepping(Y_base_lil, sources_base, v_ini)
        except ConvergenceError:
            if self.print_stuff: print("Source Stepping Failed.")

        # 4. GMIN Stepping (Floods the circuit with conductance, then drains it)
        try:
            if self.print_stuff: print("\n--- Fallback 3: GMIN Stepping ---")
            return self._gmin_stepping(Y_base_lil, sources_base, v_ini)
        except ConvergenceError:
            raise RuntimeError("CRITICAL: All convergence methods failed. Check your circuit topology for floating nodes or invalid parameters.")

    def _nr_core(self, Y_base_lil, sources_base, v_guess, alpha=1.0, gmin=0.0):
        """The pure mathematical Newton-Raphson iterative loop."""
        v_k = v_guess.copy()
        prev_v_k = v_guess.copy()
        lu = None

        for i in range(self.max_iter):
            y_iter, sources_iter = Y_base_lil.copy(), sources_base.copy()
            
            # GMIN Stepping: Add a conductance to ground to aid convergence
            if gmin > 0.0:
                for idx in range(self.circuit.total_dim):
                    y_iter[idx, idx] += gmin

            # Let polymorphic components linearize themselves
            for comp in self.circuit.components:
                comp.stamp_nonlinear(y_iter, sources_iter, prev_v_k, v_k)
            
            # Solve Linear Step
            try:
                lu, v_new = solve_linear_circuit(y_iter.tocsc(), sources_iter)
            except Exception:
                raise ConvergenceError("Matrix became singular.")

            # Check convergence
            delta_v = np.abs(v_new - v_k)
            max_error = np.max(delta_v)
            prev_v_k = v_k.copy()

            # Apply step with optional damping
            v_k = v_k + alpha * (v_new - v_k)

            if max_error < self.tol:
                if self.print_stuff: 
                    print(f"  -> Converged in {i+1} iterations (alpha={alpha}, gmin={gmin:.1e}).")
                return lu, v_k

        raise ConvergenceError(f"Failed to converge after {self.max_iter} iterations.")

    def _source_stepping(self, Y_base_lil, sources_base, v_ini):
        """Slowly scales up the independent sources from 10% to 100%."""
        num_steps = 10
        ramp = np.linspace(1.0/num_steps, 1.0, num_steps)
        v_k = v_ini.copy()
        lu = None

        for k in ramp:
            if self.print_stuff: print(f"  Source Step: {k*100:.0f}%")
            sources_k = sources_base.copy() * k
            lu, v_k = self._nr_core(Y_base_lil, sources_k, v_guess=v_k, alpha=1.0)
            
        return lu, v_k

    def _gmin_stepping(self, Y_base_lil, sources_base, v_ini):
        """Starts with a massive 1/100 Ohm conductance, steps down to 1e-12."""
        gmin_steps = np.logspace(-2, -12, num=10)
        v_k = v_ini.copy()
        lu = None

        for g in gmin_steps:
            if self.print_stuff: print(f"  GMIN Step: {g:.1e} Siemens")
            lu, v_k = self._nr_core(Y_base_lil, sources_base, v_guess=v_k, alpha=1.0, gmin=g)

        if self.print_stuff: print("  Final GMIN Cleanup Pass (0 Siemens)")
        return self._nr_core(Y_base_lil, sources_base, v_guess=v_k, alpha=1.0, gmin=0.0)
