"""
Circuit Solver Module.

This module handles the core mathematical operations for solving the matrix 
equations generated by the circuit. It includes direct sparse LU factorization 
for linear circuits and an advanced, cascading Newton-Raphson solver for 
nonlinear circuits to ensure robust convergence.
"""

import numpy as np
from scipy.sparse.linalg import splu


class ConvergenceError(Exception):
    """Custom exception raised when a nonlinear solving strategy fails to converge."""
    pass


# =========================================================================
# LINEAR SOLVERS
# =========================================================================

def solve_lu(g):
    """Performs SuperLU factorization on a sparse matrix.

    Args:
        g (scipy.sparse.csc_matrix): The Compressed Sparse Column admittance matrix.

    Returns:
        scipy.sparse.linalg.SuperLU: The factorized LU object.
        
    Raises:
        RuntimeError: If the matrix is singular, with diagnostic hints.
    """
    try:
        return splu(g)
    except RuntimeError as e:
        if "singular" in str(e).lower():
            raise RuntimeError(
                f"MNA matrix is singular — the circuit has no unique solution.\n"
                f"Common causes:\n"
                f"  - Voltage source loop (two voltage sources in parallel or in a loop)\n"
                f"  - Inductor loop with no series resistance\n"
                f"  - Floating node with no DC path to ground\n"
                f"  - Current source driving a node with no conductance to ground\n"
                f"  - No ground (node 0) connection in the circuit\n"
                f"Check that every node has a conductive path to ground and that no\n"
                f"voltage sources or inductors form a zero-resistance loop."
            ) from e
        raise


def get_node_and_branch_currents(lu, sources):
    """Solves the linear system using a pre-computed LU factorization.

    Args:
        lu (scipy.sparse.linalg.SuperLU): The factorized matrix object.
        sources (np.ndarray): The Right-Hand Side (RHS) current/voltage vector.

    Returns:
        np.ndarray: The resolved voltage and branch current vector.
    """
    return lu.solve(sources)


def solve_linear_circuit(y, sources):
    """Solves a complete linear circuit equation in one shot.

    Args:
        y (scipy.sparse.csc_matrix): The full MNA admittance matrix.
        sources (np.ndarray): The RHS source vector.

    Returns:
        tuple: (lu, vi) where `lu` is the factorized matrix object and `vi` is 
        the 1D numpy array of solved node voltages and branch currents.
    """
    lu = solve_lu(y)
    vi = get_node_and_branch_currents(lu, sources)
    return lu, vi


# =========================================================================
# NONLINEAR SOLVER
# =========================================================================

class NonlinearSolver:
    """Cascading Newton-Raphson nonlinear solver.

    Tries to solve the nonlinear circuit using standard Newton-Raphson. If it 
    fails due to singular matrices or oscillation, it progressively cascades 
    through slower but more robust strategies: Damping, Source Stepping, and 
    GMIN Stepping.

    Attributes:
        circuit (Circuit): The main circuit object.
        max_iter (int): Maximum allowed iterations per NR attempt.
        tol (float): The voltage error tolerance for convergence.
        print_stuff (bool): Toggles console logging.
    """

    def __init__(self, circuit, max_iter=100, tol=1e-6, print_stuff=True):
        """Initializes the Nonlinear Solver.

        Args:
            circuit (Circuit): The populated circuit containing components.
            max_iter (int, optional): Max iterations per NR loop. Defaults to 100.
            tol (float, optional): Convergence tolerance in Volts. Defaults to 1e-6.
            print_stuff (bool, optional): Enable console logging. Defaults to True.
        """
        self.circuit = circuit
        self.max_iter = max_iter
        self.tol = tol
        self.print_stuff = print_stuff

    def solve(self, Y_base_lil, sources_base, v_ini):
        """The Master Routing Method. Cascades through fallback options if NR fails.

        Args:
            Y_base_lil (scipy.sparse.lil_matrix): The static base admittance matrix.
            sources_base (np.ndarray): The static RHS source vector.
            v_ini (np.ndarray): The initial voltage guess vector.

        Returns:
            tuple: (lu, v_final) where `lu` is the final factorized matrix and 
            `v_final` is the converged solution array. The LU factorization is
            guaranteed to be consistent with v_final (re-factorized at convergence).

        Raises:
            RuntimeError: If all 4 convergence strategies completely fail.
        """
        # 1. Standard Newton-Raphson (Fastest)
        try:
            if self.print_stuff: print("\n--- Attempting Standard Newton-Raphson ---")
            return self._nr_core(Y_base_lil, sources_base, v_ini, alpha=1.0)
        except ConvergenceError:
            if self.print_stuff: print("Standard NR Failed.")

        # 2. Damped Newton-Raphson (Slower steps to prevent overshoot)
        try:
            if self.print_stuff: print("\n--- Fallback 1: Damped Newton-Raphson ---")
            return self._nr_core(Y_base_lil, sources_base, v_ini, alpha=0.25)
        except ConvergenceError:
            if self.print_stuff: print("Damped NR Failed.")

        # 3. Source Stepping (Slowly turns on the power supplies)
        try:
            if self.print_stuff: print("\n--- Fallback 2: Source Stepping ---")
            return self._source_stepping(Y_base_lil, sources_base, v_ini)
        except ConvergenceError:
            if self.print_stuff: print("Source Stepping Failed.")

        # 4. GMIN Stepping (Floods the circuit with conductance, then drains it)
        try:
            if self.print_stuff: print("\n--- Fallback 3: GMIN Stepping ---")
            return self._gmin_stepping(Y_base_lil, sources_base, v_ini)
        except ConvergenceError:
            raise RuntimeError(
                "CRITICAL: All convergence methods failed. "
                "Check your circuit topology for floating nodes or invalid parameters."
            )

    def _nr_core(self, Y_base_lil, sources_base, v_guess, alpha=1.0, gmin=0.0):
        """The pure mathematical Newton-Raphson iterative loop.
        
        When damping is used (alpha < 1.0), convergence is checked on the 
        actual damped update to ensure the returned LU factorization is 
        consistent with the returned solution vector. This is critical for 
        Adjoint sensitivity accuracy.
        """
        v_k = v_guess.copy()
        prev_v_k = v_guess.copy()
        lu = None

        for i in range(self.max_iter):
            y_iter, sources_iter = Y_base_lil.copy(), sources_base.copy()
            
            # GMIN Stepping: Add a conductance to ground to aid convergence
            if gmin > 0.0:
                for idx in range(self.circuit.total_dim):
                    y_iter[idx, idx] += gmin

            # Let polymorphic components linearize themselves
            for comp in self.circuit.components:
                comp.stamp_nonlinear(y_iter, sources_iter, prev_v_k, v_k)
            
            # Solve Linear Step
            try:
                lu, v_new = solve_linear_circuit(y_iter.tocsc(), sources_iter)
            except Exception:
                raise ConvergenceError("Matrix became singular.")

            # Apply step with optional damping
            prev_v_k = v_k.copy()
            v_k = v_k + alpha * (v_new - v_k)

            # Check convergence on the ACTUAL update applied (not the full Newton step).
            # This ensures that when we report convergence, v_k is truly within tolerance.
            delta_v = np.abs(v_k - prev_v_k)
            max_error = np.max(delta_v)

            if max_error < self.tol:
                if self.print_stuff: 
                    print(f"  -> Converged in {i+1} iterations (alpha={alpha}, gmin={gmin:.1e}).")
                
                # Re-factorize at the converged point so the LU exactly matches v_k.
                # This is essential for Adjoint correctness when alpha < 1.0.
                if alpha < 1.0:
                    y_final, s_final = Y_base_lil.copy(), sources_base.copy()
                    if gmin > 0.0:
                        for idx in range(self.circuit.total_dim):
                            y_final[idx, idx] += gmin
                    for comp in self.circuit.components:
                        comp.stamp_nonlinear(y_final, s_final, prev_v_k, v_k)
                    lu = solve_lu(y_final.tocsc())
                
                return lu, v_k

        raise ConvergenceError(f"Failed to converge after {self.max_iter} iterations.")

    def _source_stepping(self, Y_base_lil, sources_base, v_ini):
        """Slowly scales up the independent sources from 10% to 100%.
        
        Note: This scales the entire RHS vector, which is correct for DC bias
        computation where sources_base only contains independent source stamps.
        During transient analysis, companion model history currents should NOT
        be scaled — but in practice, the transient engine rebuilds sources_step
        from scratch each step, so this method is only invoked during the 
        initial DC operating point solve where no companion terms exist.
        """
        num_steps = 10
        ramp = np.linspace(1.0/num_steps, 1.0, num_steps)
        v_k = v_ini.copy()
        lu = None

        for k in ramp:
            if self.print_stuff: print(f"  Source Step: {k*100:.0f}%")
            sources_k = sources_base.copy() * k
            lu, v_k = self._nr_core(Y_base_lil, sources_k, v_guess=v_k, alpha=1.0)
            
        return lu, v_k

    def _gmin_stepping(self, Y_base_lil, sources_base, v_ini):
        """Starts with a massive 1/100 Ohm conductance, steps down to 1e-12."""
        gmin_steps = np.logspace(-2, -12, num=10)
        v_k = v_ini.copy()
        lu = None

        for g in gmin_steps:
            if self.print_stuff: print(f"  GMIN Step: {g:.1e} Siemens")
            lu, v_k = self._nr_core(Y_base_lil, sources_base, v_guess=v_k, alpha=1.0, gmin=g)

        if self.print_stuff: print("  Final GMIN Cleanup Pass (0 Siemens)")
        return self._nr_core(Y_base_lil, sources_base, v_guess=v_k, alpha=1.0, gmin=0.0)
